
#!/bin/bash

echo "Compiling the parallelized version of program with -fopenmp flag"
gcc -O0 -I include -DPOLYBENCH_TIME -DPOLYBENCH_DUMP_ARRAYS src/polybench.c src/correlation.c -o correlation.serial -lm -fopenmp
echo "Running the parallelized program with DUMP ARRAY to get the output to later compare with the original"
for i in {1,2,4,8}
do
	echo "Threads:	$i"
	OMP_NUM_THREADS="$i" ./correlation.serial 2> correlation.data.serial.fopenmp"$i"

done
