
#!/bin/bash

echo "Compiling the parallelized version of program with -fopenmp flag"
gcc -O0 -I include -DPOLYBENCH_TIME -DPOLYBENCH_DUMP_ARRAYS src/polybench.c src/reg_detect.c -o reg_detect.serial -lm -fopenmp
echo "Running the parallelized program with DUMP ARRAY to get the output to later compare with the original"
for i in {1,2,4,8}
do
	echo "Threads:	$i"
	OMP_NUM_THREADS="$i" ./reg_detect.serial 2> reg_detect.data.serial.fopenmp"$i"

done
